# Copyright 2021 Google LLC

# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this
# file except in compliance with the License. You may obtain a copy of the License at

# https://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS"
# BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

steps:
- name: gcr.io/cloud-builders/git
  id: git deep fetch to identify changed files
  args: ['fetch', '--unshallow']

- name: 'gcr.io/deeplearning-platform-release/tf-cpu.2-6'
  id: execute notebooks
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    TIMESTAMP=$$(date +%Y-%m-%dt%H%M%S)
    STAGING_BUCKET_NAME=asl_cloudbuild_$$TIMESTAMP
    NOTEBOOK_TEST_ALLOWLIST=$$(git diff --name-only  remotes/origin/$_HEAD_BRANCH $(git merge-base  remotes/origin/$_HEAD_BRANCH  remotes/origin/$_BASE_BRANCH) | grep \\.ipynb$$)
    gsutil mb -l $$LOCATION gs://$$STAGING_BUCKET_NAME
    for NOTEBOOK in $$NOTEBOOK_TEST_ALLOWLIST ; do
        OUTPUT_NOTEBOOK_FOLDER=gs://$$STAGING_BUCKET_NAME/$$NOTEBOOK/output
        OUTPUT_NOTEBOOK=$${NOTEBOOK}.output.ipynb
        papermill NOTEBOOK OUTPUT_NOTEBOOK
        gsutil cp $$OUTPUT_NOTEBOOK $$OUTPUT_NOTEBOOK_FOLDER/
        echo "output written to $${OUTPUT_NOTEBOOK_FOLDER}/$${OUTPUT_NOTEBOOK}"
    done
